theme: jekyll-theme-slate
title: bloggled!
description: The internet's source of bloggled blogs
timezone: Australia/Sydney
baseurl: /bloggled
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
